[[footer]]
name = "Service"
url = "https://www.gsplugins.com/services/"
weight = 2

[[footer]]
name = "Support"
url = "https://www.gsplugins.com/contact/"
weight = 1

# soial
[[social]]
name = "ti-facebook"
url = "https://www.facebook.com/gsplugins/"

[[social]]
name = "ti-twitter-alt"
url = "https://twitter.com/gsplugins"

[[social]]
name = "ti-youtube"
url = "https://www.youtube.com/channel/UCB0SU0JDMMECS9BGJtD7lzg"

[[social]]
name = "ti-linkedin"
url = "https://www.linkedin.com/company/gs-plugins"